<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/21ag24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

In [1]:
import numpy as np

In [5]:
a=[1,2,3,4]
a=np.array(a)
a

array([1, 2, 3, 4])

In [7]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [8]:
a+b

array([ 6,  8, 10, 12])

In [9]:
a*b

array([ 5, 12, 21, 32])

In [11]:
a**b

array([    1,    64,  2187, 65536])

In [13]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [14]:
a.shape

(4,)

In [17]:
a.shape[0]

4

In [23]:
a,a[-2],a[2]

(array([1, 2, 3, 4]), 3, 3)

In [26]:
#slicing
a[:2],a[2:]

(array([1, 2]), array([3, 4]))

In [30]:
a=np.array([1,2,True,4])
a

array([1, 2, 1, 4])

In [43]:
A=np.array([[1,2,3],[3,4,5]])
print(A.shape,A)

(2, 3) [[1 2 3]
 [3 4 5]]


In [44]:
A**2 #obtienes la potencia de una matriz entrada por entrada

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [46]:
A@A.T #.T te da la transpuesta de la matriz

array([[14, 26],
       [26, 50]])

In [47]:
A/A

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
B=np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


In [56]:
B[2,3]#el primer numero me dice que lista selecciono
#el segundo numero me dice que elemento voy a tomar

13

In [64]:
print(B)
print("\n")
print(B[:2])
print("\n")
print(B[2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


[[1 2 3 4]
 [5 6 7 8]]


[[10 11 12 13]]


In [71]:
print(B)
print("\n")
print(B[:2,:2])
print("\n")
print(B[:2,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


[[1 2]
 [5 6]]


[[3 4]
 [7 8]]


In [73]:
print(B)
print("\n")
print(B[:2,:])
print("\n")
print(B[:,:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


[[1 2 3 4]
 [5 6 7 8]]


[[ 1  2]
 [ 5  6]
 [10 11]]


In [75]:
print(B)
print("\n")
print(B*B)#multiplicacion entrada a entrada

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


[[  1   4   9  16]
 [ 25  36  49  64]
 [100 121 144 169]]


In [77]:
np.dot(B,B.T)#multiplicacion matricial

array([[ 30,  70, 120],
       [ 70, 174, 304],
       [120, 304, 534]])