<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/GrandSmith.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy import linalg as la

In [3]:
A=[[1,-1,4.0],[1.0,4.0,-2.],[1,4.0,2.],[1,-1.,0.]]
A=np.array(A,dtype=float)
A

array([[ 1., -1.,  4.],
       [ 1.,  4., -2.],
       [ 1.,  4.,  2.],
       [ 1., -1.,  0.]])

In [4]:

def QR(A):
  Q=np.empty_like(A) ## matriz Q
  R=np.zeros([A.shape[1],A.shape[1]]) ## matriz cuadrada
  vi=np.zeros([A.shape[1]])

  for i in range(A.shape[1]):
    vi=A[:,i]
    for j in range(i):
      R[j,i]=np.dot(Q[:,j].T,vi)
      vi = vi - R[j,i]*Q[:,j]
      #vi = a2 - (q1T, a2)* q1
    R[i,i]=np.linalg.norm(vi,2)
    Q[:,i]=vi/R[i,i]

  return Q,R

In [5]:

Q,R=QR(A)
# mostrar ambas matrices
print(Q)
print(R)

# comprobacion
print(np.matmul(Q,R))

[[ 0.5 -0.5  0.5]
 [ 0.5  0.5 -0.5]
 [ 0.5  0.5  0.5]
 [ 0.5 -0.5 -0.5]]
[[ 2.  3.  2.]
 [ 0.  5. -2.]
 [ 0.  0.  4.]]
[[ 1. -1.  4.]
 [ 1.  4. -2.]
 [ 1.  4.  2.]
 [ 1. -1.  0.]]
