<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/HouseHolder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from numpy import linalg as LA
A=np.array([[-1.,-1.,1.],[1.,3.,3.],[-1.,-1.,5.]])
b=np.ones(A.shape[0])
A

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.]])

In [ ]:
n=A.shape[0]
Q=np.eye(n)

xi=np.zeros(n)
xi[0:]=A[:,0][0:]
norm_x=LA.norm(xi)

ei=np.zeros(n)
ei[0]=1.0

ui=np.zeros(n)
ui=xi+np.sign(A[0,0])*norm_x*ei

vi= ui/LA.norm(ui)
vi=vi.reshape(-1,1)

H=np.eye(n)-2*vi@vi.T
A=H@A
Q=Q@H

A,Q

(array([[ 1.73205081,  2.88675135, -1.73205081],
        [ 0.        ,  1.57735027,  4.        ],
        [ 0.        ,  0.42264973,  4.        ]]),
 array([[-0.57735027,  0.57735027, -0.57735027],
        [ 0.57735027,  0.78867513,  0.21132487],
        [-0.57735027,  0.21132487,  0.78867513]]))

In [ ]:
xi=np.zeros(n)
xi[1:]=A[:,1][1:]
norm_x=LA.norm(xi)

ei=np.zeros(n)
ei[1]=1.0

ui=np.zeros(n)
ui=xi+np.sign(A[1,1])*norm_x*ei

vi= ui/LA.norm(ui)
vi=vi.reshape(-1,1)

H=np.eye(n)-2*vi@vi.T
A=H@A
Q=Q@H

A,Q

(array([[ 1.73205081e+00,  2.88675135e+00, -1.73205081e+00],
        [ 0.00000000e+00, -1.63299316e+00, -4.89897949e+00],
        [ 0.00000000e+00, -1.33021460e-17,  2.82842712e+00]]),
 array([[-5.77350269e-01, -4.08248290e-01, -7.07106781e-01],
        [ 5.77350269e-01, -8.16496581e-01, -6.65107298e-18],
        [-5.77350269e-01, -4.08248290e-01,  7.07106781e-01]]))

In [2]:
def Householder(A):
  Q=np.eye(len(A))
  n=A.shape[1]

  for i in range(n):
    xi=np.zeros(len(A))
    xi[i:]=A[:,i][i:]
    norm_x=LA.norm(xi)
    ei=np.zeros(len(A))
    ei[i]=1.0
    ui=np.zeros(len(A))
    ui=xi+np.sign(A[i,i])*norm_x*ei
    vi=ui/LA.norm(ui)
    vi=vi.reshape(-1,1)

    H=np.eye(len(A))-2*vi@vi.T
    A=H@A
    Q=Q@H

  return Q,A

In [ ]:
def SustAtras(U, y):
    x = np.zeros_like(y)
    n = U.shape[0]  # cantidad de renglones de U
    x[n-1] = y[n-1] / U[n-1, n-1]
    for i in range(n-2, -1, -1):
        sum = 0.0
        for j in range(i+1, n):
            sum += U[i, j] * x[j]
        x[i] = (y[i] - sum) / U[i, i]

    return x

In [10]:
#A=np.array([[-1.,-1.,1.],[1.,3.,3.],[-1.,-1.,5.],[1.,3.,7.]])
Q,R=Householder(A)
Q@R

array([[-1., -1.,  1.],
       [ 1.,  3.,  3.],
       [-1., -1.,  5.]])

In [11]:
R

array([[ 1.73205081e+00,  2.88675135e+00, -1.73205081e+00],
       [ 0.00000000e+00, -1.63299316e+00, -4.89897949e+00],
       [ 0.00000000e+00,  1.33021460e-17, -2.82842712e+00]])

In [ ]:
A_aux=Q@R
y=Q.T@b
x=SustAtras(R, y)