<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/InversaDeMatriz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from numpy import linalg as LA

In [3]:
A=np.array([[2,3,-4],[0,-4,2],[1,-1,5]])
A

array([[ 2,  3, -4],
       [ 0, -4,  2],
       [ 1, -1,  5]])

In [2]:
def SubMat(M,row,col):
  M1=np.copy(M)
  M1=np.delete(M1,row,axis=0)# elimina sobre sobre los renglones
  M1=np.delete(M1,col,axis=1)# elimina sobre sobre los renglones
  return M1

In [7]:
def DET(M):
  if len(M)==2:
    return M[0][0]*M[1][1]-(M[0][1]*M[1][0])
  else:
    deter=0.0
    for i in range(len(M)):
      deter+= ((-1)**i)*M[0][i]*DET(SubMat(M,0,i))
    return deter

In [10]:
DET(A),LA.det(A)

(-46.0, -46.0)

In [11]:
def CoFac(M):
  M_CoFa=np.zeros_like(M)

  for i in range(M.shape[0]):# va sobre renglones
    for j in range(M.shape[1]):#va sobre columnas
      M_CoFa[i][j]=((-1)**(i+j))*DET(SubMat(M,i,j))

  return M_CoFa

In [14]:
def Inv(M):
  deter=DET(M)
  M_CoFa=CoFac(M)
  return (1/deter)*M_CoFa.T

In [15]:
A_inv=Inv(A)
A_inv

array([[ 0.39130435,  0.23913043,  0.2173913 ],
       [-0.04347826, -0.30434783,  0.08695652],
       [-0.08695652, -0.10869565,  0.17391304]])

In [16]:
A@A_inv

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17, -1.38777878e-17,  1.00000000e+00]])

In [17]:
A_inv@A

array([[ 1.00000000e+00, -1.38777878e-16,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])