<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/LU_normal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([[2.0,1.0,1.0],[4.0,6.0,0.0],[-2.0,7.0,2.0]])
A

array([[ 2.,  1.,  1.],
       [ 4.,  6.,  0.],
       [-2.,  7.,  2.]])

In [3]:
np.eye(A.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
def FactLU(A):
  U=np.copy(A)
  n=A.shape[1]
  L=np.eye(A.shape[0])
  for j in range(n-1):
    Lj=np.eye(A.shape[0])
    for i in range(j+1,n):
      Lj[i][j]=-U[i][j]/U[j][j]
    print(Lj,j)
    U=Lj@U
    print(U)

In [5]:
FactLU(A)

[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 1.  0.  1.]] 0
[[ 2.  1.  1.]
 [ 0.  4. -2.]
 [ 0.  8.  3.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -2.  1.]] 1
[[ 2.  1.  1.]
 [ 0.  4. -2.]
 [ 0.  0.  7.]]
