<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/LU_normal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#A=np.array([[2.0,1.0,1.0],[4.0,-6.0,0.0],[-2.0,7.0,2.0]])
A=np.array([[-4.,-3.,1.],[8.,11.,-1.],[4.,18.,5.]])
A

array([[-4., -3.,  1.],
       [ 8., 11., -1.],
       [ 4., 18.,  5.]])

In [3]:
np.eye(A.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
def FactLU(A):
  U=np.copy(A)
  n=A.shape[1]
  L=np.eye(n)
  for j in range(n):
    Lj=np.eye(n)
    for i in range(j+1,n):
      Lj[i,j]=-U[i,j]/U[j,j]
    L=L@Lj
    #print(Lj,j)
    U=Lj@U
  L=2*np.eye(n)-L
  return L,U

In [5]:
L,U=FactLU(A)
print(U)
print(L)
print(L@U)

[[-4. -3.  1.]
 [ 0.  5.  1.]
 [ 0.  0.  3.]]
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1.  3.  1.]]
[[-4. -3.  1.]
 [ 8. 11. -1.]
 [ 4. 18.  5.]]


In [6]:
def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

In [7]:
b=np.ones(3)
x=SustDelante(L,b)
x

array([ 1.,  3., -7.])