<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/LU_normal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.array([[2.0,1.0,1.0],[4.0,-6.0,0.0],[-2.0,7.0,2.0]])
A

array([[ 2.,  1.,  1.],
       [ 4., -6.,  0.],
       [-2.,  7.,  2.]])

In [ ]:
np.eye(A.shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
def FactLU(A):
  U=np.copy(A)
  n=A.shape[1]
  L=np.eye(n)
  for j in range(n):
    Lj=np.eye(n)
    for i in range(j+1,n):
      Lj[i,j]=-U[i,j]/U[j,j]
    print(Lj,j)
    U=Lj@U
    print(U)
#ya quedo

In [ ]:
FactLU(A)

[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 1.  0.  1.]] 0
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  8.  3.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]] 1
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2
[[ 2.  1.  1.]
 [ 0. -8. -2.]
 [ 0.  0.  1.]]
