<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/LU_pivoteo_parcial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
def FactLU(A):
  U=np.copy(A)
  n=A.shape[1]
  L=np.eye(n)
  for j in range(n):
    Lj=np.eye(n)
    for i in range(j+1,n):
      Lj[i,j]=-U[i,j]/U[j,j]
    L=L@Lj
    #print(Lj,j)
    U=Lj@U
  L=2*np.eye(n)-L
  return L,U

def SustDelante(L,b):
  x=np.zeros_like(b)
  n=L.shape[0]# cantidad de renglones de L
  for i in range(n):
    sum=0.0
    for j in range(i):
      sum+=L[i,j]*x[j]
    x[i]=(b[i]-sum)/L[i,i]

  return x

def SustAtras(U,y):
  x=np.zeros_like(y)
  n=U.shape[0]# cantidad de renglones de U
  x[n-1]=y[n-1]/U[n-1][n-1]

  for i in range(n-2,-1,-1):
    sum=0.0
    for j in range(i+1,n):
      sum+=U[i,j]*x[j]
    x[i]=(y[i]-sum)/U[i,i]

  return x

def SolverLU(A,b):
  L,U=FactLU(A)
  y=SustDelante(L,b)
  x=SustAtras(U,y)

  return x

In [3]:
A=np.array([[1.,2.,4.],[2.,1.,3.],[3.,2.,4]])
A

array([[1., 2., 4.],
       [2., 1., 3.],
       [3., 2., 4.]])

In [4]:
np.argmax(A[0,:]) # ncuentra el valor máximo de la matriz
A[[0,2]]=A[[2,0]] # Intercambia el renglon 0 con el 2

In [35]:
def Permutaciones(A,y):
  Ps=[]
  U=np.copy(A)
  b=np.copy(y)

  for i in range(A.shape[0]):
    P=np.eye(A.shape[0])
    k=np.argmax(U[i:,i:])
    print(k,i)
    U[[i,k]]=U[[k,i]]
    P[[i,k]]=P[[k,i]]
    b[[i,k]]=b[[k,i]]
    Ps.append(P)

  return U,Ps,b

In [6]:
A_g,Ps,b_g=Permutaciones(A,y)
x_g=SolverLU(A_g,b_g)

array([[1., 2., 4.],
       [2., 1., 3.],
       [3., 2., 4.]])

In [34]:
Permutaciones(A)

2 0
3 1
0 2


array([[4.]])