<a href="https://colab.research.google.com/github/seismomat/Numerico2025_1/blob/main/Rotaciones_Givens_chido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy import linalg as la

In [3]:
A=[[1,-1,4.0],[1.0,4.0,-2.],[1,4.0,2.],[1,-1.,0.]]
A=np.array(A,dtype=float)
A

array([[ 1., -1.,  4.],
       [ 1.,  4., -2.],
       [ 1.,  4.,  2.],
       [ 1., -1.,  0.]])

In [4]:
def Givens(A):
  R=np.copy(A)
  Q=np.eye(len(A))
  for i in range(A.shape[1]): # maneja el pivote
    for j in range(i+1,len(A)):
      G=np.eye(len(R))
      ro=la.norm([R[i,i],R[j,i]])
      c=R[i,i]/ro
      s=R[j,i]/ro
      G[i,i]=c; G[i,j]=s;
      G[j,j]=c; G[j,i]=-s;
      R=G@R

      R=np.round(R,5)
      G=np.round(G,5)
      Q=Q@G.T
  return R,Q

In [5]:
RR,QQ=Givens(A)
print(RR)

[[ 2.       3.       2.     ]
 [ 0.       5.      -1.99999]
 [ 0.       0.       4.     ]
 [ 0.       0.      -0.     ]]


In [6]:
print(QQ)

[[ 0.50000702 -0.50000702  0.50000587 -0.50000829]
 [ 0.50000702  0.50000702 -0.50000565 -0.50000587]
 [ 0.50000242  0.50000264  0.50000702  0.50000702]
 [ 0.5        -0.50000242 -0.50000702  0.50000702]]


In [7]:
QQ@RR

array([[ 1.00001405e+00, -1.00001405e+00,  4.00004657e+00],
       [ 1.00001405e+00,  4.00005619e+00, -2.00001762e+00],
       [ 1.00000484e+00,  4.00002044e+00,  2.00003266e+00],
       [ 1.00000000e+00, -1.00001210e+00, -2.82528220e-05]])

In [8]:
A

array([[ 1., -1.,  4.],
       [ 1.,  4., -2.],
       [ 1.,  4.,  2.],
       [ 1., -1.,  0.]])